name: image_picker_plus
description: Customization of the gallery display or even camera and video.
version: 0.5.9
homepage: https://github.com/AhmedAbdoElhawary/image_picker_plus.git

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  camera: ^0.10.5+2
  image: ^4.0.17
  video_player: ^2.7.0
  image_picker: ^1.0.4
  photo_manager: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
#  photo_manager: ^3.0.0-dev.4


flutter:
  plugin:
    platforms:
      android:
        package: com.lykhonis.imagecrop
        pluginClass: ImageCropPlugin
      ios:
        pluginClass: ImageCropPlugin
